# Generated by Django 4.1.3 on 2023-01-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familia', '0004_alter_family_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
    ]
